# TensorFlow basico

In [1]:
import numpy as np
import tensorflow as tf

### Definir e rodar

In [2]:
x = tf.constant(42.0)

In [3]:
print x

Tensor("Const:0", shape=(), dtype=float32)


In [4]:
sess = tf.Session()

In [5]:
print sess.run(x)

42.0


### Grafo computacional

In [6]:
W = tf.Variable([2.], dtype=tf.float32)
b = tf.Variable([-80.], dtype=tf.float32)

In [7]:
y = W*x + b

In [8]:
sess.run(tf.global_variables_initializer())
sess.run(y)

array([ 4.], dtype=float32)

### Placehold

In [10]:
x2=tf.placeholder(tf.float32)
y2 = W*x2 + b

In [13]:
sess.run(tf.global_variables_initializer())
sess.run(y2, feed_dict={x2:[10]})

array([-60.], dtype=float32)

### Tensores

In [14]:
A = tf.constant([[1,2],[3,4]], dtype=tf.float32)
B = tf.constant([[5,6],[7,8]], dtype=tf.float32)
C = A + B
print sess.run(C)

[[  6.   8.]
 [ 10.  12.]]


In [15]:
A = tf.constant([[[1,2],[3,4]], [[1,2],[3,4]]], dtype=tf.float32)
B = tf.constant([[[5,6],[7,8]], [[5,6],[7,8]]] , dtype=tf.float32)
C = A + B
print sess.run(C)

[[[  6.   8.]
  [ 10.  12.]]

 [[  6.   8.]
  [ 10.  12.]]]


Imagens tem multiplos canais de cores, logo elas podem ser vistas como um tensor de rank 3